### ISSUE TITLE
Allow a configurable amount of just emeralds for villagers to follow

### ISSUE THREAD

**Issue by piebaker** [enjarai/smart-villagers-follow-emeralds#1]
A config option for the amount of emeralds required to get a villager to follow would be great. It could range from a stack of emerald blocks down to a single emerald itself. A sensible default could be 5 emeralds to require some investment before getting them to move around.

**Comment by enjarai** [comment]
While this would make sense to have, all configuration of the mod currently happens via datapacks, and I don't see a way to integrate this into that currently. As an alternative, you could limit the items that villagers follow to only emerald blocks?
